### ISSUE TITLE
使用paddleclas训练PPHGNetV2时报错：OSError: (External) CUDNN error(9), CUDNN_STATUS_NOT_SUPPORTED.

### ISSUE THREAD

**Issue by XianlinYao** [PaddlePaddle/PaddleClas#3365]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas release/2.6和PaddlePaddle 2.6.2
 2. 在训练PPHGNet时没有出现过问题，只在训练PPHGNetV2产生如下报错
 3. 训练环境信息：
  a. 具体操作系统：Rocky8
  b. Python版本号：3.11.11
  c. CUDA/cuDNN版本：CUDA:12.0, cuDNN:8.
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log
 LAUNCH INFO 2025-04-03 11:11:51,923 ------------------------- ERROR LOG DETAIL -------------------------
och_id, print_batch_step)
  File "/home/admin/PaddleClas/ppcls/engine/train/train.py", line 52, in train_epoch
    out = forward(engine, batch)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/PaddleClas/ppcls/engine/train/train.py", line 98, in forward
    return engine.model(batch[0])
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/anaconda3/envs/paddle_env/lib/python3.11/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/PaddleClas/ppcls/arch/backbone/legendary_models/pp_hgnet_v2.py", line 488, in forward
    x = stage(x)
        ^^^^^^^^
  File "/home/admin/anaconda3/envs/paddle_env/lib/python3.11/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/PaddleClas/ppcls/arch/backbone/legendary_models/pp_hgnet_v2.py", line 389, in forward
    x = self.blocks(x)
        ^^^^^^^^^^^^^^
  File "/home/admin/anaconda3/envs/paddle_env/lib/python3.11/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/anaconda3/envs/paddle_env/lib/python3.11/site-packages/paddle/nn/layer/container.py", line 614, in forward
    input = layer(input)
            ^^^^^^^^^^^^
  File "/home/admin/anaconda3/envs/paddle_env/lib/python3.11/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/PaddleClas/ppcls/arch/backbone/legendary_models/pp_hgnet_v2.py", line 322, in forward
    x = self.aggregation_squeeze_conv(x)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/anaconda3/envs/paddle_env/lib/python3.11/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/PaddleClas/ppcls/arch/backbone/legendary_models/pp_hgnet_v2.py", line 133, in forward
    x = self.conv(x)
        ^^^^^^^^^^^^
  File "/home/admin/anaconda3/envs/paddle_env/lib/python3.11/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/anaconda3/envs/paddle_env/lib/python3.11/site-packages/paddle/nn/layer/conv.py", line 715, in forward
    out = F.conv._conv_nd(
          ^^^^^^^^^^^^^^^^
  File "/home/admin/anaconda3/envs/paddle_env/lib/python3.11/site-packages/paddle/nn/functional/conv.py", line 128, in _conv_nd
    pre_bias = _C_ops.conv2d(
               ^^^^^^^^^^^^^^
OSError: (External) CUDNN error(9), CUDNN_STATUS_NOT_SUPPORTED.
  [Hint: 'CUDNN_STATUS_NOT_SUPPORTED'.  The functionality requested is not presently supported by cuDNN.  ] (at /paddle/paddle/phi/backends/gpu/cuda/cudnn_desc.h:162)

**Comment by XianlinYao** [comment]
切换了cuda11.8+cudnn8.6.0依然存在如上的问题

**Comment by Bobholamovic** [comment]
请问安装的paddlepaddle版本是什么样的呀？

**Comment by XianlinYao** [comment]
> 请问安装的paddlepaddle版本是什么样的呀？

用的2.6.2

**Comment by Bobholamovic** [comment]
这个问题有可能是paddlepaddle编译时使用的cuda、cudnn版本和运行时的cuda、cudnn版本不兼容导致的，所以可能还需要确认一下paddlepaddle编译使用的cuda、cudnn版本。通常这就是在官网查看安装指令时选择的环境。

**Comment by XianlinYao** [comment]
paddle给出的版本信息如下：
paddle.version.show()
full_version: 2.6.2
major: 2
minor: 6
patch: 2
rc: 0
cuda: 11.8
cudnn: 8.6.0
xpu: False
xpu_xccl: False
cinn: False
run_check()的信息如下：
paddle.utils.run_check()
Running verify PaddlePaddle program ...
I0407 11:14:06.629125 2436418 program_interpreter.cc:212] New Executor is Running.
W0407 11:14:06.630439 2436418 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 12.8, Runtime API Version: 11.8
W0407 11:14:06.661489 2436418 gpu_resources.cc:164] device: 0, cuDNN Version: 8.6.
I0407 11:14:06.923547 2436418 interpreter_util.cc:624] Standalone Executor is Used.
PaddlePaddle works well on 1 GPU.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
重新配置的环境完全和推荐配置一样了，目前是B6这个模型运行不了会报错，还有就是B4_ssld准确率跑出来比较低，可能只有9%，其余模型倒是能够正常进行训练

**Comment by XianlinYao** [comment]
> 这个问题有可能是paddlepaddle编译时使用的cuda、cudnn版本和运行时的cuda、cudnn版本不兼容导致的，所以可能还需要确认一下paddlepaddle编译使用的cuda、cudnn版本。通常这就是在官网查看安装指令时选择的环境。

paddle给出的版本信息如下：
paddle.version.show()
full_version: 2.6.2
major: 2
minor: 6
patch: 2
rc: 0
cuda: 11.8
cudnn: 8.6.0
xpu: False
xpu_xccl: False
cinn: False
run_check()的信息如下：
paddle.utils.run_check()
Running verify PaddlePaddle program ...
I0407 11:14:06.629125 2436418 program_interpreter.cc:212] New Executor is Running.
W0407 11:14:06.630439 2436418 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 12.8, Runtime API Version: 11.8
W0407 11:14:06.661489 2436418 gpu_resources.cc:164] device: 0, cuDNN Version: 8.6.
I0407 11:14:06.923547 2436418 interpreter_util.cc:624] Standalone Executor is Used.
PaddlePaddle works well on 1 GPU.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
重新配置的环境完全和推荐配置一样了，目前是B6这个模型运行不了会报错，还有就是B4_ssld准确率跑出来比较低，可能只有9%，其余模型倒是能够正常进行训练

**Comment by Bobholamovic** [comment]
请问B6模型是报什么错呀？另外B4模型是如何测试准确率的呢？

**Comment by XianlinYao** [comment]
> 请问B6模型是报什么错呀？另外B4模型是如何测试准确率的呢？
B6模型报错就如我问题描述那样，如下：
OSError: (External) CUDNN error(9), CUDNN_STATUS_NOT_SUPPORTED.
[Hint: 'CUDNN_STATUS_NOT_SUPPORTED'. The functionality requested is not presently supported by cuDNN. ] (at /paddle/paddle/phi/backends/gpu/cuda/cudnn_desc.h:162)
B4 ssld的准确率就是看train log的输出，大概只有9%上下

**Comment by XianlinYao** [comment]
> 请问B6模型是报什么错呀？另外B4模型是如何测试准确率的呢？

请问B6模型是报什么错呀？另外B4模型是如何测试准确率的呢？
B6模型报错就如我问题描述那样，如下：
OSError: (External) CUDNN error(9), CUDNN_STATUS_NOT_SUPPORTED.
[Hint: 'CUDNN_STATUS_NOT_SUPPORTED'. The functionality requested is not presently supported by cuDNN. ] (at /paddle/paddle/phi/backends/gpu/cuda/cudnn_desc.h:162)
B4 ssld的准确率就是看train log的输出，大概只有9%上下

**Comment by Bobholamovic** [comment]
1. 正常来说不太应该出现这个问题，我建议更换环境中的cuDNN为8.9试试。
2. 是整个训练完成之后只有9%吗？使用的数据集和官方默认的一致吗？

**Comment by XianlinYao** [comment]
> 1. 正常来说不太应该出现这个问题，我建议更换环境中的cuDNN为8.9试试。
> 2. 是整个训练完成之后只有9%吗？使用的数据集和官方默认的一致吗？

使用的是我们自己的数据集：），如果我想用我自己的数据集训练需要对配置进行哪些修改呢

**Comment by Bobholamovic** [comment]
如果使用的是自己的数据集的话，精度是没有保证的，通常需要经过调参才能使精度达到期望的水平。你可以尝试根据自己的数据集与原数据集在规模等方面的差异调整超参数，例如增加迭代数、增大batch size、降低学习率等。这方面属于“炼丹”的一部分，没有标准答案，可以多尝试哈～

**Comment by XianlinYao** [comment]
> 1. 正常来说不太应该出现这个问题，我建议更换环境中的cuDNN为8.9试试。
> 2. 是整个训练完成之后只有9%吗？使用的数据集和官方默认的一致吗？

cudnn用8.9的话，cuda建议是12.0版本吗还是说11.8呢

**Comment by Bobholamovic** [comment]
cuda保持11.8

**Comment by XianlinYao** [comment]
> cuda保持11.8

具体到cudnn的小版本推荐使用哪个呢，我用了8.9.7也是会出现如主题描述一样的问题

**Comment by Bobholamovic** [comment]
如果8.9.7也不行的话，我怀疑是框架的bug了，建议可以到paddle框架提一个issue～

**Comment by Bobholamovic** [comment]
如果方便的话，也可以试试升级最新的paddle 3.0版本，说不定这个问题已经解决了

**Comment by XianlinYao** [comment]
> 如果方便的话，也可以试试升级最新的paddle 3.0版本，说不定这个问题已经解决了

升级到paddle3.0问题也还是存在的，那我在paddle那边提一下吧：D

**Comment by Bobholamovic** [comment]
好的，那这个issue我先关闭了，有其他问题欢迎提问

**Comment by XianlinYao** [comment]
> 好的，那这个issue我先关闭了，有其他问题欢迎提问
感谢
